version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/node:22.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

  test:
    docker:
      - image: cimg/node:22.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:  |
          echo "Username is set: ${DOCKER_USERNAME:+yes}"
          echo "Registry is set: ${PARAM_REGISTRY:+yes}"
      - docker/check
      - docker/build:
          image: tatzelcat/nodeapp_repo
          tag: latest
      - docker/push:
          image: tatzelcat/nodeapp_repo
          tag: latest

workflows:
  build-and-push:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
