version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/node:22.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

  test:
    docker:
      - image: cimg/node:22.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  
  publish:
     executor: docker/docker
     steps:
       - setup_remote_docker
       - checkout
       - docker/check:
              docker-username: DOCKERHUB_LOGIN  
              docker-password: DOCKERHUB_PASSWORD 
       - docker/build:
           image: mrcicil/test-repo
       - docker/push:
           image: mrcicil/test-repo

workflows:
  build-and-push:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
    context: docker-creds
